#!/bin/bash
mkdir -p ./build/x86_64-unknown-linux-gnu/obj/

clang -c ./src/kina-runtime.c -o ./build/x86_64-unknown-linux-gnu/obj/kina-runtime.o
ar rcs ./build/x86_64-unknown-linux-gnu/kina-runtime.a ./build/x86_64-unknown-linux-gnu/obj/*