#!/bin/bash

# Find the activate script name (~/.espressif/tools/activate_???.sh)
activate_script=$(find ~/.espressif/tools -name "activate_*.sh" | head -1)

echo "Activating ESP-IDF environment using: $activate_script"

# We run inside bash -c so that $0 is "bash", bypassing the check in the ESP-IDF
# activation script that restricts execution when the script itself is run.
bash -c 'source "$1" && "$2" "$3"' bash "$activate_script" ./builder/src/index.ts xtensa-esp32-elf